name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          docker-compose build  # Builds the images as defined in your docker-compose.yml

      - name: Add SSH key for Lightsail
        run: |
          echo "${{ secrets.AWS_LIGHTSAIL_PEM_KEY }}" > lightsail-key.pem
          chmod 400 lightsail-key.pem

      - name: Deploy to AWS Lightsail
        run: |
          ssh -i lightsail-key.pem -o "StrictHostKeyChecking=no" ubuntu@50.19.188.65 << 'EOF'
          # Navigate to your application directory
          cd /home/ubuntu/app/docker-server

          # Pull the latest code from the repository
          git pull

          # Bring down any running containers and remove them
          docker-compose down

          # Run the docker-compose to build and start containers
          docker-compose up --build -d
          EOF
